id: dabench-321-there-outliers-scoremargin
name: DABench Task - Are there any outliers in the SCOREMARGIN column?
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-321-there-outliers-scoremargin/prepared/private/answer.csv
  sample_submission: dabench-321-there-outliers-scoremargin/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
