id: iwildcam-2019-fgvc6
name: iWildCam 2019 - FGVC6
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: iwildcam-2019-fgvc6/prepared/private/answers.csv
  sample_submission: iwildcam-2019-fgvc6/prepared/public/sample_submission.csv
grader:
  name: macro-f1-score
  grade_fn: grade:grade
preparer: prepare:prepare
