id: dabench-663-scatter-plot-high
name: DABench Task - Create a scatter plot of the 'High' and 'Low' colu
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-663-scatter-plot-high/description.md

dataset:
  answers: dabench-663-scatter-plot-high/prepared/private/answer.csv
  sample_submission: dabench-663-scatter-plot-high/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-663-scatter-plot-high.grade:grade

preparer: mlebench.competitions.dabench-663-scatter-plot-high.prepare:prepare
