id: dabench-124-there-significant-difference
name: DABench Task - Is there a significant difference in the total num
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-124-there-significant-difference/description.md

dataset:
  answers: dabench-124-there-significant-difference/prepared/private/answer.csv
  sample_submission: dabench-124-there-significant-difference/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-124-there-significant-difference.grade:grade

preparer: mlebench.competitions.dabench-124-there-significant-difference.prepare:prepare
