id: dabench-465-distribution-offender-ages
name: DABench Task - 2. Is the distribution of offender ages normally d
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-465-distribution-offender-ages/description.md

dataset:
  answers: dabench-465-distribution-offender-ages/prepared/private/answer.csv
  sample_submission: dabench-465-distribution-offender-ages/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-465-distribution-offender-ages.grade:grade

preparer: mlebench.competitions.dabench-465-distribution-offender-ages.prepare:prepare
