id: see-click-predict-fix
name: See Click Predict Fix
competition_type: simple
awards_medals: false
description: mlebench/competitions/see-click-predict-fix/description.md

dataset:
  answers: see-click-predict-fix/prepared/private/test.csv
  sample_submission: see-click-predict-fix/prepared/public/sample_submission.csv

grader:
  name: rmsle
  grade_fn: mlebench.competitions.see_click_predict_fix.grade:grade

preparer: mlebench.competitions.see_click_predict_fix.prepare:prepare
