id: dabench-683-what-mean-temperature
name: DABench Task - 1. What is the mean temperature recorded in the da
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-683-what-mean-temperature/prepared/private/answer.csv
  sample_submission: dabench-683-what-mean-temperature/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
