id: dabench-26-correlation-coefficient-between
name: DABench Task - Calculate the correlation coefficient between the
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-26-correlation-coefficient-between/prepared/private/answer.csv
  sample_submission: dabench-26-correlation-coefficient-between/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
