id: sciencebench-005-dkpes-model-development-1
name: "ScienceBench - dkpes_model_development_1.py"
competition_type: code
awards_medals: false
prizes: null
description: benchmarks/sciencebench/competitions/sciencebench-005-dkpes-model-development-1/description.md

dataset:
  answers: sciencebench-005-dkpes-model-development-1/prepared/private/answer.csv
  sample_submission: sciencebench-005-dkpes-model-development-1/prepared/public/sample_submission.csv

grader:
  name: rmse
  grade_fn: benchmarks.sciencebench.competitions.sciencebench-005-dkpes-model-development-1.grade:grade

preparer: benchmarks.sciencebench.competitions.sciencebench-005-dkpes-model-development-1.prepare:prepare
