id: see-click-predict-fix
name: See Click Predict Fix
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: see-click-predict-fix/prepared/private/test.csv
  sample_submission: see-click-predict-fix/prepared/public/sample_submission.csv
grader:
  name: rmsle
  grade_fn: grade:grade
preparer: prepare:prepare
