id: dabench-674-build-machine-learning
name: DABench Task - Build a machine learning model to predict the Medi
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-674-build-machine-learning/prepared/private/answer.csv
  sample_submission: dabench-674-build-machine-learning/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
