id: dabench-722-identify-vehicle-with
name: DABench Task - 1. Identify the vehicle with the highest horsepowe
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-722-identify-vehicle-with/description.md

dataset:
  answers: dabench-722-identify-vehicle-with/prepared/private/answer.csv
  sample_submission: dabench-722-identify-vehicle-with/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-722-identify-vehicle-with.grade:grade

preparer: mlebench.competitions.dabench-722-identify-vehicle-with.prepare:prepare
