id: tmdb-box-office-prediction
name: TMDB Box Office Prediction
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: tmdb-box-office-prediction/prepared/private/test.csv
  sample_submission: tmdb-box-office-prediction/prepared/public/sample_submission.csv
grader:
  name: rmsle
  grade_fn: grade:grade
preparer: prepare:prepare
