id: dabench-427-many-storms-have
name: DABench Task - 3. How many storms have null values in the "min_p"
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-427-many-storms-have/description.md

dataset:
  answers: dabench-427-many-storms-have/prepared/private/answer.csv
  sample_submission: dabench-427-many-storms-have/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-427-many-storms-have.grade:grade

preparer: mlebench.competitions.dabench-427-many-storms-have.prepare:prepare
