id: dabench-659-find-correlation-between
name: DABench Task - Find the correlation between the 'High' and 'Low' 
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-659-find-correlation-between/description.md

dataset:
  answers: dabench-659-find-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-659-find-correlation-between/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-659-find-correlation-between.grade:grade

preparer: mlebench.competitions.dabench-659-find-correlation-between.prepare:prepare
