id: dabench-337-distribution-median-sold
name: DABench Task - 2. Is the distribution of the median sold price pe
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-337-distribution-median-sold/description.md

dataset:
  answers: dabench-337-distribution-median-sold/prepared/private/answer.csv
  sample_submission: dabench-337-distribution-median-sold/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-337-distribution-median-sold.grade:grade

preparer: mlebench.competitions.dabench-337-distribution-median-sold.prepare:prepare
