id: plant-seedlings-classification
name: Plant Seedlings Classification
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: plant-seedlings-classification/prepared/private/answers.csv
  sample_submission: plant-seedlings-classification/prepared/public/sample_submission.csv
grader:
  name: micro-f1-score
  grade_fn: grade:grade
preparer: prepare:prepare
