id: dabench-58-what-percentage-missing
name: DABench Task - What is the percentage of missing values in the "N
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-58-what-percentage-missing/prepared/private/answer.csv
  sample_submission: dabench-58-what-percentage-missing/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
