id: dabench-350-fare-column-follows
name: DABench Task - Check if the Fare column follows a normal distribu
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-350-fare-column-follows/prepared/private/answer.csv
  sample_submission: dabench-350-fare-column-follows/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
