id: sciencebench-001-clintox-nn
name: "ScienceBench - clintox_nn"
competition_type: code
awards_medals: false
prizes: null
description: benchmarks/sciencebench/competitions/sciencebench-001-clintox-nn/description.md

dataset:
  answers: sciencebench-001-clintox-nn/prepared/private/answer.csv
  sample_submission: sciencebench-001-clintox-nn/prepared/public/sample_submission.csv

grader:
  name: roc_auc
  grade_fn: benchmarks.sciencebench.competitions.sciencebench-001-clintox-nn.grade:grade

preparer: benchmarks.sciencebench.competitions.sciencebench-001-clintox-nn.prepare:prepare
