id: dabench-575-using-feature-engineering
name: DABench Task - Using feature engineering techniques, create a new
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-575-using-feature-engineering/prepared/private/answer.csv
  sample_submission: dabench-575-using-feature-engineering/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
