id: dabench-425-many-missing-values
name: DABench Task - 1. How many missing values are there in the "max_s
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-425-many-missing-values/description.md

dataset:
  answers: dabench-425-many-missing-values/prepared/private/answer.csv
  sample_submission: dabench-425-many-missing-values/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-425-many-missing-values.grade:grade

preparer: mlebench.competitions.dabench-425-many-missing-values.prepare:prepare
