id: dabench-359-distribution-wind-speed
name: DABench Task - Check if the distribution of wind speed in the wea
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-359-distribution-wind-speed/prepared/private/answer.csv
  sample_submission: dabench-359-distribution-wind-speed/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
