id: dabench-247-what-average-number
name: DABench Task - What is the average number of runs scored by playe
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-247-what-average-number/description.md

dataset:
  answers: dabench-247-what-average-number/prepared/private/answer.csv
  sample_submission: dabench-247-what-average-number/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-247-what-average-number.grade:grade

preparer: mlebench.competitions.dabench-247-what-average-number.prepare:prepare
