id: dabench-8-distribution-analysis-fare
name: DABench Task - Perform a distribution analysis on the 'Fare' colu
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-8-distribution-analysis-fare/description.md

dataset:
  answers: dabench-8-distribution-analysis-fare/prepared/private/answer.csv
  sample_submission: dabench-8-distribution-analysis-fare/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-8-distribution-analysis-fare.grade:grade

preparer: mlebench.competitions.dabench-8-distribution-analysis-fare.prepare:prepare
