id: dabench-8-distribution-analysis-fare
name: DABench Task - Perform a distribution analysis on the 'Fare' colu
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-8-distribution-analysis-fare/prepared/private/answer.csv
  sample_submission: dabench-8-distribution-analysis-fare/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
