id: dabench-716-data-preprocessing-dropping
name: DABench Task - 1. Perform data preprocessing by dropping the rows
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-716-data-preprocessing-dropping/description.md

dataset:
  answers: dabench-716-data-preprocessing-dropping/prepared/private/answer.csv
  sample_submission: dabench-716-data-preprocessing-dropping/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-716-data-preprocessing-dropping.grade:grade

preparer: mlebench.competitions.dabench-716-data-preprocessing-dropping.prepare:prepare
