id: dabench-734-there-correlation-between
name: DABench Task - Is there a correlation between life expectancy and
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-734-there-correlation-between/description.md

dataset:
  answers: dabench-734-there-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-734-there-correlation-between/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-734-there-correlation-between.grade:grade

preparer: mlebench.competitions.dabench-734-there-correlation-between.prepare:prepare
