id: dabench-116-there-outliers-happiness
name: DABench Task - Are there any outliers in the happiness scores of
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-116-there-outliers-happiness/prepared/private/answer.csv
  sample_submission: dabench-116-there-outliers-happiness/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
