id: dabench-9-mean-value-close
name: DABench Task - Calculate the mean value of the "Close Price" colu
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-9-mean-value-close/prepared/private/answer.csv
  sample_submission: dabench-9-mean-value-close/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
