id: dabench-59-among-countries-americas
name: DABench Task - Among the countries in the "Americas" region, whic
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-59-among-countries-americas/prepared/private/answer.csv
  sample_submission: dabench-59-among-countries-americas/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
