id: dabench-738-distribution-column-credit
name: DABench Task - Check if the distribution of the "Age" column in t
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-738-distribution-column-credit/prepared/private/answer.csv
  sample_submission: dabench-738-distribution-column-credit/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
