id: dabench-310-correlation-analysis-numerical
name: DABench Task - Perform a correlation analysis on the numerical va
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-310-correlation-analysis-numerical/prepared/private/answer.csv
  sample_submission: dabench-310-correlation-analysis-numerical/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
