id: dabench-690-outlier-detection-wind
name: DABench Task - 2. Perform outlier detection on the wind speed col
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-690-outlier-detection-wind/prepared/private/answer.csv
  sample_submission: dabench-690-outlier-detection-wind/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
