id: dabench-480-feature-engineering-techniques
name: DABench Task - Apply feature engineering techniques to the datase
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-480-feature-engineering-techniques/description.md

dataset:
  answers: dabench-480-feature-engineering-techniques/prepared/private/answer.csv
  sample_submission: dabench-480-feature-engineering-techniques/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-480-feature-engineering-techniques.grade:grade

preparer: mlebench.competitions.dabench-480-feature-engineering-techniques.prepare:prepare
