id: dabench-426-what-maximum-sustained
name: DABench Task - 2. What is the maximum sustained wind speed record
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-426-what-maximum-sustained/description.md

dataset:
  answers: dabench-426-what-maximum-sustained/prepared/private/answer.csv
  sample_submission: dabench-426-what-maximum-sustained/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-426-what-maximum-sustained.grade:grade

preparer: mlebench.competitions.dabench-426-what-maximum-sustained.prepare:prepare
