id: dogs-vs-cats-redux-kernels-edition
name: 'Dogs vs. Cats Redux: Kernels Edition'
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dogs-vs-cats-redux-kernels-edition/prepared/private/answers.csv
  sample_submission: dogs-vs-cats-redux-kernels-edition/prepared/public/sample_submission.csv
grader:
  name: log-loss
  grade_fn: grade:grade
preparer: prepare:prepare
