id: demand-forecasting-kernels-only
name: Demand Forecasting Kernels Only
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: demand-forecasting-kernels-only/prepared/private/test.csv
  sample_submission: demand-forecasting-kernels-only/prepared/public/sample_submission.csv
grader:
  name: smape
  grade_fn: grade:grade
preparer: prepare:prepare
