id: dabench-414-what-average-passengers
name: DABench Task - What is the average age of passengers in each tick
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-414-what-average-passengers/description.md

dataset:
  answers: dabench-414-what-average-passengers/prepared/private/answer.csv
  sample_submission: dabench-414-what-average-passengers/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-414-what-average-passengers.grade:grade

preparer: mlebench.competitions.dabench-414-what-average-passengers.prepare:prepare
