id: ventilator-pressure-prediction
name: Ventilator Pressure Prediction
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: ventilator-pressure-prediction/prepared/private/test.csv
  sample_submission: ventilator-pressure-prediction/prepared/public/sample_submission.csv
grader:
  name: mae
  grade_fn: grade:grade
preparer: prepare:prepare
