id: predict-volcanic-eruptions-ingv-oe
name: INGV - Volcanic Eruption Prediction
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: predict-volcanic-eruptions-ingv-oe/prepared/private/test.csv
  sample_submission: predict-volcanic-eruptions-ingv-oe/prepared/public/sample_submission.csv
grader:
  name: mean-absolute-error
  grade_fn: grade:grade
preparer: prepare:prepare
