id: dabench-743-comprehensive-data-preprocessing
name: DABench Task - Perform a comprehensive data preprocessing on the
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-743-comprehensive-data-preprocessing/prepared/private/answer.csv
  sample_submission: dabench-743-comprehensive-data-preprocessing/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
