id: dabench-33-column-normally-distributed
name: DABench Task - Is the "row m/z" column normally distributed?
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-33-column-normally-distributed/description.md

dataset:
  answers: dabench-33-column-normally-distributed/prepared/private/answer.csv
  sample_submission: dabench-33-column-normally-distributed/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-33-column-normally-distributed.grade:grade

preparer: mlebench.competitions.dabench-33-column-normally-distributed.prepare:prepare
