id: dabench-650-there-correlation-between
name: DABench Task - 2. Is there any correlation between the X-coordina
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-650-there-correlation-between/description.md

dataset:
  answers: dabench-650-there-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-650-there-correlation-between/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-650-there-correlation-between.grade:grade

preparer: mlebench.competitions.dabench-650-there-correlation-between.prepare:prepare
