id: dabench-542-what-mean-length
name: DABench Task - What is the mean length of the abalone in mm?
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-542-what-mean-length/prepared/private/answer.csv
  sample_submission: dabench-542-what-mean-length/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
