id: dabench-554-what-median-value
name: DABench Task - What is the median HT_M value for the plant specie
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-554-what-median-value/description.md

dataset:
  answers: dabench-554-what-median-value/prepared/private/answer.csv
  sample_submission: dabench-554-what-median-value/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-554-what-median-value.grade:grade

preparer: mlebench.competitions.dabench-554-what-median-value.prepare:prepare
