id: dabench-473-there-outliers-value
name: DABench Task - Are there any outliers in the "Value" column? If y
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-473-there-outliers-value/description.md

dataset:
  answers: dabench-473-there-outliers-value/prepared/private/answer.csv
  sample_submission: dabench-473-there-outliers-value/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-473-there-outliers-value.grade:grade

preparer: mlebench.competitions.dabench-473-there-outliers-value.prepare:prepare
