id: dabench-760-each-station-there
name: DABench Task - 6. For each station, are there any missing values
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-760-each-station-there/prepared/private/answer.csv
  sample_submission: dabench-760-each-station-there/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
