id: dabench-351-determine-correlation-coefficient
name: DABench Task - Determine the correlation coefficient between Age 
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-351-determine-correlation-coefficient/description.md

dataset:
  answers: dabench-351-determine-correlation-coefficient/prepared/private/answer.csv
  sample_submission: dabench-351-determine-correlation-coefficient/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-351-determine-correlation-coefficient.grade:grade

preparer: mlebench.competitions.dabench-351-determine-correlation-coefficient.prepare:prepare
