id: playground-series-s3e1
name: Playground Series S3E1
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: playground-series-s3e1/prepared/private/test.csv
  sample_submission: playground-series-s3e1/prepared/public/sample_submission.csv
grader:
  name: rmse
  grade_fn: grade:grade
preparer: prepare:prepare
