id: dabench-174-determine-skewness-fares
name: DABench Task - Determine the skewness of the fares paid by the pa
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-174-determine-skewness-fares/description.md

dataset:
  answers: dabench-174-determine-skewness-fares/prepared/private/answer.csv
  sample_submission: dabench-174-determine-skewness-fares/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-174-determine-skewness-fares.grade:grade

preparer: mlebench.competitions.dabench-174-determine-skewness-fares.prepare:prepare
