id: dabench-249-there-significant-correlation
name: DABench Task - Is there a significant correlation between the num
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-249-there-significant-correlation/prepared/private/answer.csv
  sample_submission: dabench-249-there-significant-correlation/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
