id: dabench-300-there-correlation-between
name: DABench Task - 1. Is there a correlation between the "nsnps" and
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-300-there-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-300-there-correlation-between/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
