id: dabench-432-predict-maximum-sustained
name: DABench Task - 2. Can we predict the maximum sustained wind speed
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-432-predict-maximum-sustained/description.md

dataset:
  answers: dabench-432-predict-maximum-sustained/prepared/private/answer.csv
  sample_submission: dabench-432-predict-maximum-sustained/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-432-predict-maximum-sustained.grade:grade

preparer: mlebench.competitions.dabench-432-predict-maximum-sustained.prepare:prepare
