id: dabench-5-generate-feature-called
name: DABench Task - Generate a new feature called "FamilySize" by summ
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-5-generate-feature-called/prepared/private/answer.csv
  sample_submission: dabench-5-generate-feature-called/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
