id: dabench-70-machine-learning-training
name: DABench Task - Perform machine learning by training a linear regr
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-70-machine-learning-training/prepared/private/answer.csv
  sample_submission: dabench-70-machine-learning-training/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
