id: dabench-224-utilize-machine-learning
name: DABench Task - Utilize machine learning techniques to classify th
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-224-utilize-machine-learning/prepared/private/answer.csv
  sample_submission: dabench-224-utilize-machine-learning/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
