id: liverpool-ion-switching
name: Liverpool Ion Switching
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: liverpool-ion-switching/prepared/private/test.csv
  sample_submission: liverpool-ion-switching/prepared/public/sample_submission.csv
grader:
  name: macro-f1
  grade_fn: grade:grade
preparer: prepare:prepare
