id: iwildcam-2020-fgvc7
name: iWildCam 2020 - FGVC7
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: iwildcam-2020-fgvc7/prepared/private/answers.csv
  sample_submission: iwildcam-2020-fgvc7/prepared/public/sample_submission.csv
grader:
  name: accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
