id: herbarium-2022-fgvc9
name: Herbarium 2022 - FGVC9
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: herbarium-2022-fgvc9/prepared/private/answers.csv
  sample_submission: herbarium-2022-fgvc9/prepared/public/sample_submission.csv
grader:
  name: macro-f1-score
  grade_fn: grade:grade
preparer: prepare:prepare
