id: dabench-352-identify-outliers-fare
name: DABench Task - Identify any outliers in the Fare column using the
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-352-identify-outliers-fare/prepared/private/answer.csv
  sample_submission: dabench-352-identify-outliers-fare/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
