id: dabench-472-what-mean-value
name: DABench Task - What is the mean value of the "Value" column?
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-472-what-mean-value/description.md

dataset:
  answers: dabench-472-what-mean-value/prepared/private/answer.csv
  sample_submission: dabench-472-what-mean-value/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-472-what-mean-value.grade:grade

preparer: mlebench.competitions.dabench-472-what-mean-value.prepare:prepare
