id: dabench-446-what-mean-wind
name: DABench Task - 1. What is the mean wind speed in the dataset?
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-446-what-mean-wind/description.md

dataset:
  answers: dabench-446-what-mean-wind/prepared/private/answer.csv
  sample_submission: dabench-446-what-mean-wind/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-446-what-mean-wind.grade:grade

preparer: mlebench.competitions.dabench-446-what-mean-wind.prepare:prepare
