id: dabench-755-what-mean-value
name: DABench Task - 1. What is the mean value of the maximum temperatu
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-755-what-mean-value/description.md

dataset:
  answers: dabench-755-what-mean-value/prepared/private/answer.csv
  sample_submission: dabench-755-what-mean-value/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-755-what-mean-value.grade:grade

preparer: mlebench.competitions.dabench-755-what-mean-value.prepare:prepare
