id: dabench-721-find-correlation-coefficient
name: DABench Task - 3. Find the correlation coefficient between the 'm
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-721-find-correlation-coefficient/prepared/private/answer.csv
  sample_submission: dabench-721-find-correlation-coefficient/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
