id: text-normalization-challenge-russian-language
name: Text Normalization Challenge - Russian Language
competition_type: simple
awards_medals: true
prizes:
- position: 1
  value: 12000
- position: 2
  value: 8000
- position: 3
  value: 5000
description: description.md
dataset:
  answers: text-normalization-challenge-russian-language/prepared/private/answers.csv
  sample_submission: text-normalization-challenge-russian-language/prepared/private/sample_submission.csv
grader:
  name: accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
