id: instant-gratification
name: Instant Gratification
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: instant-gratification/prepared/private/test.csv
  sample_submission: instant-gratification/prepared/public/sample_submission.csv
grader:
  name: auc-roc
  grade_fn: grade:grade
preparer: prepare:prepare
