id: dabench-450-average-wind-speed
name: "DABench Task - 2. Calculate the average wind speed (WINDSPEED) fo"
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-450-average-wind-speed/description.md

dataset:
  answers: dabench-450-average-wind-speed/prepared/private/answer.csv
  sample_submission: dabench-450-average-wind-speed/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-450-average-wind-speed.grade:grade

preparer: mlebench.competitions.dabench-450-average-wind-speed.prepare:prepare
