id: liverpool-ion-switching
name: Liverpool Ion Switching
competition_type: simple
awards_medals: false
description: mlebench/competitions/liverpool-ion-switching/description.md

dataset:
  answers: liverpool-ion-switching/prepared/private/test.csv
  sample_submission: liverpool-ion-switching/prepared/public/sample_submission.csv

grader:
  name: macro-f1
  grade_fn: mlebench.competitions.liverpool_ion_switching.grade:grade

preparer: mlebench.competitions.liverpool_ion_switching.prepare:prepare
