id: dabench-179-pearson-correlation-coefficient
name: DABench Task - Calculate the Pearson correlation coefficient betw
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-179-pearson-correlation-coefficient/prepared/private/answer.csv
  sample_submission: dabench-179-pearson-correlation-coefficient/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
