id: dabench-308-feature-engineering-techniques
name: DABench Task - Use feature engineering techniques to create a new
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-308-feature-engineering-techniques/description.md

dataset:
  answers: dabench-308-feature-engineering-techniques/prepared/private/answer.csv
  sample_submission: dabench-308-feature-engineering-techniques/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-308-feature-engineering-techniques.grade:grade

preparer: mlebench.competitions.dabench-308-feature-engineering-techniques.prepare:prepare
