id: playground-series-s3e11
name: Playground Series S3E11
competition_type: simple
awards_medals: false
description: description.md
dataset:
  answers: playground-series-s3e11/prepared/private/test.csv
  sample_submission: playground-series-s3e11/prepared/public/sample_submission.csv
grader:
  name: rmsle
  grade_fn: grade:grade
preparer: prepare:prepare
