id: dabench-506-what-average-number
name: DABench Task - 1. What is the average number of reviews per hotel
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-506-what-average-number/description.md

dataset:
  answers: dabench-506-what-average-number/prepared/private/answer.csv
  sample_submission: dabench-506-what-average-number/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-506-what-average-number.grade:grade

preparer: mlebench.competitions.dabench-506-what-average-number.prepare:prepare
