id: dabench-424-develop-machine-learning
name: DABench Task - 3. Develop a machine learning model to classify th
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-424-develop-machine-learning/description.md

dataset:
  answers: dabench-424-develop-machine-learning/prepared/private/answer.csv
  sample_submission: dabench-424-develop-machine-learning/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-424-develop-machine-learning.grade:grade

preparer: mlebench.competitions.dabench-424-develop-machine-learning.prepare:prepare
