id: dabench-55-what-mean-number
name: DABench Task - What is the mean number of cases recorded across a
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-55-what-mean-number/prepared/private/answer.csv
  sample_submission: dabench-55-what-mean-number/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
