id: dabench-176-median-male-passengers
name: DABench Task - Calculate the median age of male passengers who su
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-176-median-male-passengers/description.md

dataset:
  answers: dabench-176-median-male-passengers/prepared/private/answer.csv
  sample_submission: dabench-176-median-male-passengers/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-176-median-male-passengers.grade:grade

preparer: mlebench.competitions.dabench-176-median-male-passengers.prepare:prepare
