id: dabench-355-linear-regression-analysis
name: DABench Task - Perform a linear regression analysis to predict fa
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-355-linear-regression-analysis/prepared/private/answer.csv
  sample_submission: dabench-355-linear-regression-analysis/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
