id: petfinder-pawpularity-score
name: PetFinder.my - Pawpularity Contest
competition_type: code
awards_medals: true
prizes:
- position: 1
  value: 12000
- position: 2
  value: 8000
- position: 3
  value: 5000
description: description.md
dataset:
  answers: petfinder-pawpularity-score/prepared/private/test.csv
  sample_submission: petfinder-pawpularity-score/prepared/public/sample_submission.csv
grader:
  name: root-mean-squared-error
  grade_fn: grade:grade
preparer: prepare:prepare
