id: dabench-304-fare-variable-follows
name: DABench Task - Check if the fare variable follows a normal distri
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-304-fare-variable-follows/description.md

dataset:
  answers: dabench-304-fare-variable-follows/prepared/private/answer.csv
  sample_submission: dabench-304-fare-variable-follows/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-304-fare-variable-follows.grade:grade

preparer: mlebench.competitions.dabench-304-fare-variable-follows.prepare:prepare
