id: spooky-author-identification
name: Spooky Author Identification
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: spooky-author-identification/prepared/private/test.csv
  sample_submission: spooky-author-identification/prepared/public/sample_submission.csv
grader:
  name: multi-class-log-loss
  grade_fn: grade:grade
preparer: prepare:prepare
