id: sciencebench-051-brain-blood-qsar
name: ScienceBench - brain_blood_qsar.py
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: sciencebench-051-brain-blood-qsar/prepared/private/answer.csv
  sample_submission: sciencebench-051-brain-blood-qsar/prepared/public/sample_submission.csv
grader:
  name: balanced_accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
