competition_type: generic
dataset:
  answers: my-custom-task-01/prepared/private/answer.csv
  sample_submission: my-custom-task-01/prepared/public/sample.csv
description: description.md
grader:
  grade_fn: simple_accuracy_grader:simple_accuracy_grader
id: my-custom-task-01
metric: RMSE
name: Bike Sharing Demand Prediction
preparer: prepare:prepare
private_dir: my-custom-task-01/prepared/private
public_dir: my-custom-task-01/prepared/public
raw_dir: my-custom-task-01/raw
task_type: regression
