id: dabench-105-correlation-coefficient-between
name: DABench Task - Calculate the correlation coefficient between Appl
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-105-correlation-coefficient-between/prepared/private/answer.csv
  sample_submission: dabench-105-correlation-coefficient-between/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: mlebench.competitions.dabench-105-correlation-coefficient-between.prepare:prepare
