id: dabench-140-question-there-correlation
name: "DABench Task - Question 3: Is there a correlation between the num"
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-140-question-there-correlation/description.md

dataset:
  answers: dabench-140-question-there-correlation/prepared/private/answer.csv
  sample_submission: dabench-140-question-there-correlation/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-140-question-there-correlation.grade:grade

preparer: mlebench.competitions.dabench-140-question-there-correlation.prepare:prepare
