id: dabench-572-identify-date-with
name: DABench Task - Identify the date with the highest closing value o
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-572-identify-date-with/prepared/private/answer.csv
  sample_submission: dabench-572-identify-date-with/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
