id: spaceship-titanic
name: Spaceship Titanic
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: spaceship-titanic/prepared/private/test.csv
  sample_submission: spaceship-titanic/prepared/public/sample_submission.csv
grader:
  name: accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
