id: dabench-733-feature-engineering-techniques
name: DABench Task - Apply feature engineering techniques to create a n
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-733-feature-engineering-techniques/prepared/private/answer.csv
  sample_submission: dabench-733-feature-engineering-techniques/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
