id: dabench-589-generate-feature-representing
name: DABench Task - Can we generate a new feature representing the cal
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-589-generate-feature-representing/prepared/private/answer.csv
  sample_submission: dabench-589-generate-feature-representing/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
