id: dabench-513-among-hotels-with
name: DABench Task - 2. Among the hotels with a star rating, what is th
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-513-among-hotels-with/prepared/private/answer.csv
  sample_submission: dabench-513-among-hotels-with/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
