id: dabench-39-explore-distribution-importance
name: DABench Task - Explore the distribution of the "importance.score"
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-39-explore-distribution-importance/description.md

dataset:
  answers: dabench-39-explore-distribution-importance/prepared/private/answer.csv
  sample_submission: dabench-39-explore-distribution-importance/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-39-explore-distribution-importance.grade:grade

preparer: mlebench.competitions.dabench-39-explore-distribution-importance.prepare:prepare
