id: dabench-529-identify-patterns-relationships
name: DABench Task - Can you identify any patterns or relationships bet
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-529-identify-patterns-relationships/description.md

dataset:
  answers: dabench-529-identify-patterns-relationships/prepared/private/answer.csv
  sample_submission: dabench-529-identify-patterns-relationships/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-529-identify-patterns-relationships.grade:grade

preparer: mlebench.competitions.dabench-529-identify-patterns-relationships.prepare:prepare
