id: dabench-529-identify-patterns-relationships
name: DABench Task - Can you identify any patterns or relationships bet
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-529-identify-patterns-relationships/prepared/private/answer.csv
  sample_submission: dabench-529-identify-patterns-relationships/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
