id: dabench-465-distribution-offender-ages
name: DABench Task - 2. Is the distribution of offender ages normally d
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-465-distribution-offender-ages/prepared/private/answer.csv
  sample_submission: dabench-465-distribution-offender-ages/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
