id: dabench-429-there-correlation-between
name: DABench Task - 2. Is there a correlation between the maximum stor
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-429-there-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-429-there-correlation-between/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
