id: dabench-658-volume-column-adheres
name: DABench Task - Check if the 'Volume' column adheres to a normal d
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-658-volume-column-adheres/prepared/private/answer.csv
  sample_submission: dabench-658-volume-column-adheres/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
