id: paddy-disease-classification
name: 'Paddy Doctor: Paddy Disease Classification'
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: paddy-disease-classification/prepared/private/test.csv
  sample_submission: paddy-disease-classification/prepared/public/sample_submission.csv
grader:
  name: accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
