id: dabench-363-train-machine-learning
name: DABench Task - Train a machine learning model to predict the amou
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-363-train-machine-learning/description.md

dataset:
  answers: dabench-363-train-machine-learning/prepared/private/answer.csv
  sample_submission: dabench-363-train-machine-learning/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-363-train-machine-learning.grade:grade

preparer: mlebench.competitions.dabench-363-train-machine-learning.prepare:prepare
