id: dabench-35-identify-remove-outliers
name: DABench Task - Identify and remove any outliers in the "row reten
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-35-identify-remove-outliers/prepared/private/answer.csv
  sample_submission: dabench-35-identify-remove-outliers/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
