id: random-acts-of-pizza
name: Random Acts of Pizza
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: random-acts-of-pizza/prepared/private/test.csv
  sample_submission: random-acts-of-pizza/prepared/public/sampleSubmission.csv
grader:
  name: auc-roc
  grade_fn: grade:grade
preparer: prepare:prepare
