id: dabench-11-correlation-coefficient-between
name: DABench Task - Calculate the correlation coefficient between the 
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-11-correlation-coefficient-between/description.md

dataset:
  answers: dabench-11-correlation-coefficient-between/prepared/private/answer.csv
  sample_submission: dabench-11-correlation-coefficient-between/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-11-correlation-coefficient-between.grade:grade

preparer: mlebench.competitions.dabench-11-correlation-coefficient-between.prepare:prepare
