id: dabench-588-there-outliers-average
name: DABench Task - Are there any outliers in the average wait time fo
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-588-there-outliers-average/prepared/private/answer.csv
  sample_submission: dabench-588-there-outliers-average/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
