id: dabench-553-many-outliers-there
name: DABench Task - How many outliers are there in the TPH_PLT column?
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-553-many-outliers-there/description.md

dataset:
  answers: dabench-553-many-outliers-there/prepared/private/answer.csv
  sample_submission: dabench-553-many-outliers-there/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-553-many-outliers-there.grade:grade

preparer: mlebench.competitions.dabench-553-many-outliers-there.prepare:prepare
