id: dabench-18-mean-standard-deviation
name: DABench Task - Calculate the mean and standard deviation of the "
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-18-mean-standard-deviation/prepared/private/answer.csv
  sample_submission: dabench-18-mean-standard-deviation/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
