id: dabench-268-meanpot-values-normally
name: DABench Task - Are the MEANPOT values normally distributed in the
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-268-meanpot-values-normally/description.md

dataset:
  answers: dabench-268-meanpot-values-normally/prepared/private/answer.csv
  sample_submission: dabench-268-meanpot-values-normally/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-268-meanpot-values-normally.grade:grade

preparer: mlebench.competitions.dabench-268-meanpot-values-normally.prepare:prepare
