id: ethanol-concentration
name: Ethanol Concentration Time Series Classification
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: ethanol-concentration/prepared/private/test_labels.csv
  sample_submission: ethanol-concentration/prepared/public/sample_submission.csv
grader:
  name: accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
