id: dabench-111-comprehensive-data-preprocessing
name: DABench Task - Perform comprehensive data preprocessing by handli
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-111-comprehensive-data-preprocessing/description.md

dataset:
  answers: dabench-111-comprehensive-data-preprocessing/prepared/private/answer.csv
  sample_submission: dabench-111-comprehensive-data-preprocessing/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-111-comprehensive-data-preprocessing.grade:grade

preparer: mlebench.competitions.dabench-111-comprehensive-data-preprocessing.prepare:prepare
