id: dabench-530-there-correlation-between
name: DABench Task - Is there a correlation between the age of the pass
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-530-there-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-530-there-correlation-between/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
