id: dabench-277-there-correlation-between
name: DABench Task - Is there any correlation between the MedInd and La
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-277-there-correlation-between/description.md

dataset:
  answers: dabench-277-there-correlation-between/prepared/private/answer.csv
  sample_submission: dabench-277-there-correlation-between/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-277-there-correlation-between.grade:grade

preparer: mlebench.competitions.dabench-277-there-correlation-between.prepare:prepare
