id: dabench-210-identify-remove-outliers
name: DABench Task - 1. Identify and remove any outliers in the "neg" s
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-210-identify-remove-outliers/prepared/private/answer.csv
  sample_submission: dabench-210-identify-remove-outliers/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
