id: dabench-208-mean-standard-deviation
name: DABench Task - 2. Calculate the mean and standard deviation of th
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-208-mean-standard-deviation/description.md

dataset:
  answers: dabench-208-mean-standard-deviation/prepared/private/answer.csv
  sample_submission: dabench-208-mean-standard-deviation/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-208-mean-standard-deviation.grade:grade

preparer: mlebench.competitions.dabench-208-mean-standard-deviation.prepare:prepare
