id: plant-pathology-2020-fgvc7
name: Plant Pathology 2020 - FGVC7
competition_type: simple
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: plant-pathology-2020-fgvc7/prepared/private/test.csv
  sample_submission: plant-pathology-2020-fgvc7/prepared/public/sample_submission.csv
grader:
  name: mean-column-wise-roc-auc
  grade_fn: grade:grade
preparer: prepare:prepare
