id: dabench-254-identify-outliers-gross
name: DABench Task - Identify any outliers in the gross domestic produc
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-254-identify-outliers-gross/prepared/private/answer.csv
  sample_submission: dabench-254-identify-outliers-gross/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
