id: dabench-468-there-outliers-distribution
name: DABench Task - 2. Are there any outliers in the age distribution 
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-468-there-outliers-distribution/description.md

dataset:
  answers: dabench-468-there-outliers-distribution/prepared/private/answer.csv
  sample_submission: dabench-468-there-outliers-distribution/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-468-there-outliers-distribution.grade:grade

preparer: mlebench.competitions.dabench-468-there-outliers-distribution.prepare:prepare
