id: dabench-278-there-outliers-agri
name: DABench Task - Are there any outliers in the Agri column of the d
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: dabench-278-there-outliers-agri/prepared/private/answer.csv
  sample_submission: dabench-278-there-outliers-agri/prepared/public/sample_submission.csv
grader:
  name: exact_match
  grade_fn: grade:grade
preparer: prepare:prepare
