id: dabench-667-medinc-column-adheres
name: DABench Task - Check if the MedInc column adheres to a normal dis
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-667-medinc-column-adheres/description.md

dataset:
  answers: dabench-667-medinc-column-adheres/prepared/private/answer.csv
  sample_submission: dabench-667-medinc-column-adheres/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-667-medinc-column-adheres.grade:grade

preparer: mlebench.competitions.dabench-667-medinc-column-adheres.prepare:prepare
