id: bike-sharing-demand
name: Bike Sharing Demand
competition_type: simple
task_type: kaggle
awards_medals: false
description: description.md
dataset:
  answers: bike-sharing-demand/prepared/private/test_answer.csv
  sample_submission: bike-sharing-demand/prepared/public/sampleSubmission.csv
grader:
  name: rmsle
  grade_fn: grade:grade
preparer: mlebench.competitions.bike_sharing_demand.prepare:prepare
