id: dabench-741-feature-credit-file
name: DABench Task - Create a new feature in the Credit.csv file by cal
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-741-feature-credit-file/description.md

dataset:
  answers: dabench-741-feature-credit-file/prepared/private/answer.csv
  sample_submission: dabench-741-feature-credit-file/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-741-feature-credit-file.grade:grade

preparer: mlebench.competitions.dabench-741-feature-credit-file.prepare:prepare
