id: dabench-321-there-outliers-scoremargin
name: DABench Task - Are there any outliers in the SCOREMARGIN column? 
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-321-there-outliers-scoremargin/description.md

dataset:
  answers: dabench-321-there-outliers-scoremargin/prepared/private/answer.csv
  sample_submission: dabench-321-there-outliers-scoremargin/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-321-there-outliers-scoremargin.grade:grade

preparer: mlebench.competitions.dabench-321-there-outliers-scoremargin.prepare:prepare
