id: imet-2020-fgvc7
name: iMet Collection 2020 - FGVC7
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: imet-2020-fgvc7/prepared/private/answers.csv
  sample_submission: imet-2020-fgvc7/prepared/public/sample_submission.csv
grader:
  name: micro-f1-score
  grade_fn: grade:grade
preparer: prepare:prepare
