id: dabench-551-what-mean-column
name: DABench Task - What is the mean of the DBH_CM column?
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-551-what-mean-column/description.md

dataset:
  answers: dabench-551-what-mean-column/prepared/private/answer.csv
  sample_submission: dabench-551-what-mean-column/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-551-what-mean-column.grade:grade

preparer: mlebench.competitions.dabench-551-what-mean-column.prepare:prepare
