id: histopathologic-cancer-detection
name: Histopathologic Cancer Detection
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: histopathologic-cancer-detection/prepared/private/answers.csv
  sample_submission: histopathologic-cancer-detection/prepared/public/sample_submission.csv
grader:
  name: auc-roc
  grade_fn: grade:grade
preparer: prepare:prepare
