id: dabench-56-which-country-highest
name: DABench Task - Which country has the highest number of deaths rec
competition_type: code
awards_medals: false
prizes: null
description: mlebench/competitions/dabench-56-which-country-highest/description.md

dataset:
  answers: dabench-56-which-country-highest/prepared/private/answer.csv
  sample_submission: dabench-56-which-country-highest/prepared/public/sample_submission.csv

grader:
  name: exact_match
  grade_fn: mlebench.competitions.dabench-56-which-country-highest.grade:grade

preparer: mlebench.competitions.dabench-56-which-country-highest.prepare:prepare
