id: sciencebench-015-aai
name: ScienceBench - aai.py
competition_type: code
awards_medals: false
prizes: null
description: description.md
dataset:
  answers: sciencebench-015-aai/prepared/private/answer.csv
  sample_submission: sciencebench-015-aai/prepared/public/sample_submission.csv
grader:
  name: accuracy
  grade_fn: grade:grade
preparer: prepare:prepare
